name: Orbis Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  SDK_VERSION: 0.0.1.487
  OO_PS4_TOOLCHAIN: /opt/OpenOrbis/PS4Toolchain

jobs:
  build-ps4:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld llvm make git libelf-dev

      - name: Setup OpenOrbis PS4 Toolchain
        run: |
          echo "Downloading Toolchain..."
          wget https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/download/${{ env.SDK_VERSION }}/toolchain.tar.gz -O toolchain.tar.gz
          
          export OO_PS4_TOOLCHAIN=${{ env.OO_PS4_TOOLCHAIN }}
          
          echo "Creating directory and extracting..."
          tar -xzf toolchain.tar.gz -C /opt
          
          echo "Toolchain setup complete."
      - name: Install LibSSL 1.1
        run: |
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository -y ppa:rael-gc/rvm
          sudo apt-get install -y libssl-dev=1.1.1l-1ubuntu1.4 --allow-downgrades

      - name: Pull Build Rules
        run: wget -P $OO_PS4_TOOLCHAIN https://github.com/bucanero/oosdk_libraries/raw/refs/heads/master/build_rules.mk

      - name: Debug
        run: |
          ls -la /opt
          ls -la $OO_PS4_TOOLCHAIN
          ls -la /opt/OpenOrbis/PS4Toolchain/include

      - name: Build Project
        run: |
          make

      - name: ls -la
        run: ls -la

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS4-Binary
          path: |
            libSQLite.a